<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="MAIN" Id="{c2782fdd-b80e-4ae7-a3a3-9440492aedf8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Pippo	: BOOL;
	Paperino : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Pippo := TRUE;
Paperino := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>